# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='file_tyoe',
            new_name='file_type',
        ),
    ]
